### ISSUE TITLE
MongoDB TF collection structure at indexing time

### ISSUE THREAD

**Issue by gheorghelisca** [code-iai/ros-mongodb_log#6]
The current structure of MongoDB TF collection is:

=============================================================================

- object[0]
  - _id
  - transforms
    - stampedtransform[0]
    - ...
    - stampedtransform[n]
  - __recorded
  - __topic
- ...
- object[n]

=============================================================================

- Why do we specially need the fiels: _id, __recorded and __topic?

- Wouldn't be enough a structure of MongoDB TF collection like this:

=============================================================================

- stampedtransform[0]
- ...
- stampedtransform[n]

=============================================================================

storing each stampedtransform as separate object instead of clustering them into arrays and only after having the arrays as documents?

The main reason I am asking this is because when we want to index TF collection on the field "transforms.header.stamp" which is contained into an array. When MongoDB has to index a field which contains an array (in our case transforms) it creates a multi key index [1]  which is slower than a single key index.
There is an EXCEPTION though: in case the indexed field contains the same value for all array elements (all stamps of stamped_transforms fields) then MongoDB decides (automatically) to build a simple key index.
So far in the case of "fetch and place" TF data, all stamped transforms from the same array share the same timestamp. In my opinion this is the reason why so far for "fetch and place" data, MongoDB didn't build a multi key index.
In case of "dna extraction data" the stamped transforms contained into the same array don't share the same time stamp, hence a multi key index is being build and the queries are slower.

My proposition is to simplify the structure of the database and give up on using arrays for storing more stamped transforms together (I cannot see the advantage of doing this. Please share it with me if you know one). This change would avoid the main reason why MongoDB could create a multi key index on indexing the TF collection on stamp field.

[1] http://docs.mongodb.org/manual/core/index-multikey/

**Comment by knowrob** [comment]
The _id field is required by MongoDB as a unique identifier for each record. The __recorded and __topic fields are added by the logger to store where the content of this collection came from. In my opinion, these are important since they allow to replay the data in the database, similar to rosbag play. AFAIK, the mongodb_store project has already implemented such functionality.

What I like about the current structure is that there is a direct correspondence between what you see on the /tf topic and what you have in the DB, which is useful for documentation/logging purposes, but also when it comes to replaying the data. If we reorganize too much, we need a special treatment for each kind of data, while the current version allows a generic 'mongodb_play' script. In addition, restructuring the data at logging time, especially for a high-volume topic such as tf, may cause performance issues.

**Comment by airballking** [comment]
I also think that the structure of the MongoDB collections was made to mimic the structure of the original ROS message to allow behavior like ```rosbag play``` from the DB.

To come back to Gheorghe's issue: I __suspect__ that your issue lies actually in the way you publish transforms to ```tf``` from ```CRAM```. Meaning: Why do you have various different time-stamps in the same ROS message? I think the ```robot-state-publisher``` tries to avoid this for performance reasons. 

@gheorghelisca Could you please gives us an excerpt of a collection of transforms which have different time-stamps? My suspicion is that they come from ```CRAM``` and not the ```robot-state-publisher```. Maybe this will help us get rid of your problem at the root. :)

**Comment by airballking** [comment]
Gheorghe and me just had a look at this lisp code for publishing transforms to ```tf```. The problem is there:

https://github.com/gheorghelisca/roslisp_common/blob/tf2_devel/cl_tf2/src/broadcaster.lisp#L67

While iterating over a list of transforms to publish, the broadcaster continously gets a new timestamp from ```ros-time```. So, we hope he can fix his problem now.

**Comment by gheorghelisca** [comment]
I didn't know that all stamped transforms from a TF message must share the same timestamp. When publishing on ```/tf```from ```CRAM``` I didn't care at all about this aspect.

Here [1] is an excerpt of a collection of transforms which have different time-stamps [2] and indeed the transforms coming from CRAM don't fulfill this assumption :)

With respect to the current structure I understand why it looks like this, so I will update the CRAM part publishing the TF messages.

[1] tf_record_braking_the_index.json
[2] https://www.dropbox.com/sh/7m8eywo8h37wwms/AABs9dEvyBIwAgEJqPpZrhUTa?dl=0

**Comment by knowrob** [comment]
I think, in general they don't have to have identical time stamps. All of them will get thrown into the common buffer anyways, and the tf client interpolates between them. It's mainly the indexing issue that you have pointed to that requires identical time stamps.

**Comment by gheorghelisca** [comment]
@airballking Very nice observation Georg! Thanks a lot! :) I made the updates you point me at and now everything works fine.

@knowrob Thanks a lot for enlightening me on how the logger suppose to work :)

I am very happy now it works well :)
